version: '3.8'

services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ai-service-prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - WORKERS=4
      - DEBUG=false
      # Project IP configuration
      - PROJECT_IP=${PROJECT_IP:-192.168.6.11}
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ENABLE_ELASTICSEARCH_AUTH=false
      # 🔒 SECURITY: CRITICAL environment variables
      - ES_HOST=${ES_HOST:-elasticsearch}
      - ES_PORT=${ES_PORT:-9200}
      - ES_USERNAME=${ES_USERNAME:-}
      - ES_PASSWORD=${ES_PASSWORD:-}
      - ES_SCHEME=${ES_SCHEME:-http}
      - ES_VERIFY_CERTS=${ES_VERIFY_CERTS:-false}
      - ADMIN_API_KEY=${ADMIN_API_KEY:-}
      - ENABLE_SEARCH_CACHE=true
      - SEARCH_CACHE_SIZE=2000
      - QUERY_CACHE_SIZE=5000
      # Critical escalation settings
      - ENABLE_SEARCH=true
      - SEARCH_ESCALATION_THRESHOLD=0.6
      - VECTOR_SEARCH_THRESHOLD=0.3
      - ENABLE_VECTOR_FALLBACK=true
      # Elasticsearch index configuration
      - ES_AC_INDEX=sanctions_ac_patterns
      - ES_VECTOR_INDEX=vectors
      # Force reload sanctions for debugging
      - FORCE_RELOAD_SANCTIONS=true
      # Enable ES-based fuzzy search for better performance
      - ENABLE_ES_FUZZY_SEARCH=true
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - ./src/ai_service/data:/app/src/ai_service/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      elasticsearch:
        condition: service_healthy


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-prod
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=ai-service-cluster
      - node.name=ai-service-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped


  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana-prod
    environment:
      - ELASTICSEARCH_HOSTS=http://95.217.84.234:9200
      - SERVER_NAME=kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - monitoring

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - PROJECT_IP=${PROJECT_IP:-192.168.6.11}
    depends_on:
      - ai-service
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  elasticsearch_data:
    driver: local
